name: ci
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npm run test